'use strict'

// `remark-stringify` options
exports.settings = {
  // Keep these sorted alphabetically.
  bullet: '*',
  emphasis: '_',
  listItemIndent: '1',
  rule: '-',
  strong: '*',
  tightDefinitions: true,
}

exports.plugins = [
  // Keep these sorted alphabetically.
  [require('remark-lint-blockquote-indentation'), 2],
  [require('remark-lint-checkbox-character-style'), {checked: 'x', unchecked: ' '}],
  [require('remark-lint-code-block-style'), 'fenced'],
  [require('remark-lint-emphasis-marker'), '_'],
  [require('remark-lint-fenced-code-flag'), {allowEmpty: false}],
  [require('remark-lint-fenced-code-marker'), '`'],
  [require('remark-lint-file-extension'), 'md'],
  [require('remark-lint-heading-style'), 'atx'],
  [require('remark-lint-linebreak-style'), 'unix'],
  [require('remark-lint-link-title-style'), '"'],
  [require('remark-lint-list-item-indent'), 'space'],
  [require('remark-lint-maximum-line-length'), 80],
  [require('remark-lint-ordered-list-marker-style'), '.'],
  [require('remark-lint-ordered-list-marker-value'), 'ordered'],
  [require('remark-lint-rule-style'), '---'],
  [require('remark-lint-strong-marker'), '*'],
  [require('remark-lint-table-cell-padding'), 'padded'],
  [require('remark-lint-unordered-list-marker-style'), '*'],
  [require('remark-retext'), require('unified')().use(require('retext-preset-stoicism'))],
  require('remark-lint-definition-case'),
  require('remark-lint-definition-spacing'),
  require('remark-lint-final-definition'),
  require('remark-lint-final-newline'),
  require('remark-lint-hard-break-spaces'),
  require('remark-lint-heading-increment'),
  require('remark-lint-list-item-bullet-indent'),
  require('remark-lint-list-item-content-indent'),
  require('remark-lint-no-auto-link-without-protocol'),
  require('remark-lint-no-blockquote-without-marker'),
  require('remark-lint-no-consecutive-blank-lines'),
  require('remark-lint-no-duplicate-defined-urls'),
  require('remark-lint-no-duplicate-definitions'),
  require('remark-lint-no-duplicate-headings'),
  require('remark-lint-no-empty-url'),
  require('remark-lint-no-file-name-articles'),
  require('remark-lint-no-file-name-consecutive-dashes'),
  require('remark-lint-no-file-name-irregular-characters'),
  require('remark-lint-no-file-name-mixed-case'),
  require('remark-lint-no-file-name-outer-dashes'),
  require('remark-lint-no-heading-content-indent'),
  require('remark-lint-no-inline-padding'),
  require('remark-lint-no-literal-urls'),
  require('remark-lint-no-multiple-toplevel-headings'),
  require('remark-lint-no-reference-like-url'),
  require('remark-lint-no-shell-dollars'),
  require('remark-lint-no-shortcut-reference-image'),
  require('remark-lint-no-shortcut-reference-link'),
  require('remark-lint-no-table-indentation'),
  require('remark-lint-no-tabs'),
  require('remark-lint-no-undefined-references'),
  require('remark-lint-no-unused-definitions'),
  require('remark-lint-table-pipe-alignment'),
  require('remark-lint-table-pipes'),
  require('remark-validate-links'),
]
